### ISSUE TITLE
Better deal with bad primes in CRA

### ISSUE THREAD

**Issue by ClementPernet** [linbox-team/linbox#100]
For the moment, minpoly over integers does a few mod p computations to guess the degree and then starts a CRA.
Instead this check should be embedded in the CRA system as follows:
 - the Iteration function class keeps the previous degree information and output an enum value saying either continue, skip or restart
 - the CRA manager the deals with these values before invoking the progress of the CRA builder

**Comment by dsroche** [comment]
I realized this will create an issue with multithreading CRA. There will be multiple Iteration functions executing simultaneously, but they somehow need their combined information to know whether the output should be "continue" or "restart". So this doesn't seem like the right way to go, but I'm not sure what is at the moment.

**Comment by ClementPernet** [comment]
The probability of a restart being so small, I would advocate for a weaker check in the context of multithreaded computations: 
- each iteration function output a value based only on its local experience
- whenever a restart is reached by one node, then the manager clears the CRA builder
- worst case scenario is when at the end of the computation, no restart has been raised, but one or a few node did compute with all wrong primes. This is extremely unlikely to happen. Eventhough, I think the builder could then make a final check and clear the CRA builder if it happens.
Does it sound reasonable?

**Comment by dsroche** [comment]
Well, I think the worst case scenario would be that one thread completes the entire computation with a too-low degree and gets the wrong answer.

I guess that would be more likely to happen on relatively small bit-length instances, e.g., if each thread is doing just a single iteration, and one thread gets a bad prime, how will it know?

Nonetheless I agree that the interface should remain the same. It is up to the algorithm to pass the Iterator object which knows about failure, so it would be possible for that object to save some state and update it in a thread-safe way if needed.

I will get going with this update and we'll see what crops up. (The multithreaded CRA doesn't seem to be working for me at the moment anyway, so that will be something to look at next.)
