### ISSUE TITLE
test-order-basis segfaults at 32bits

### ISSUE THREAD

**Issue by bdsaunders** [linbox-team/linbox#17]
zebra:~/sandbox/linbox/tests> test-order-basis rep
Writing report data to rep

Segmentation fault (core dumped)
zebra:~/sandbox/linbox/tests> cat rep
\###  matrix series is of size 64 x 32 of degree 32
\# starting sigma basis computation over Fp[x] with p=786433
zebra:~/sandbox/linbox/tests>

**Comment by bdsaunders** [comment]
That's the SmallField case.  It hangs in the LargeField case:

zebra:~/sandbox/linbox/tests> test-order-basis -b 30 rep ; echo $?
Writing report data to rep

^C
zebra:~/sandbox/linbox/tests> cat rep
###  matrix series is of size 64 x 32 of degree 32
# starting sigma basis computation over LargeField Fp[x] with p=976382117

**Comment by pascalgiorgi** [comment]
The problem with SmallField has been fixed. It was a problem with the allocation strategy on 32 bits machine that is not compatible with SIMD. We should re-use allocator from FFLAS-FPACK for vectors in order to guarantee SIMD compatibility. This could be fixed with a templated alias:
template<class T> using Vector = vector<T, AlignedAllocator<T,Alignment::DEFAULT>>;

I am still working on the LargeField hanging bug.

P.

**Comment by pascalgiorgi** [comment]
The problem with LargeField has been fixed. The problem came from the usage of 1UL instead of 1ULL.
Normally, no more bugs on 32 bits with order basis.
