### ISSUE TITLE
ftbfs on armhf, bus errors in the test suite

### ISSUE THREAD

**Issue by d-torrance** [linbox-team/linbox#238]
From [Debian bug #944055](https://bugs.debian.org/944055):

> linbox ftbfs on armhf, bus errors in the test suite, like
```
../build-aux/test-driver: line 107: 21585 Bus error               "$@" >
$log_file 2>&1
FAIL: test-smith-form-valence 
```
> the builders are now machines with 64bit kernels, and that looks like an
> alignment error.
> 
> full build log at
> https://buildd.debian.org/status/fetch.php?pkg=linbox&arch=armhf&ver=1.6.3-1&stamp=1568385253&raw=0
> 
> the package also fails on mipsel, didn't look for the reasons.

**Comment by tobihan** [comment]
This happens when linbox is built in an armhf chroot on a arm64 kernel. The bus error happens for instance in test-serialization.C, test_basic_type<int64_t>() when unserialize() is called on line 51.

Both armhf and arm64 are little endian and this is correctly detected by configure.

**Comment by plugwash** [comment]
Looking at the code.

value = *reinterpret_cast<const int64_t*>(uValue);

Casting pointers like this is not safe. Firstly because of alignment issues like the one reported here, and secondly because modern compilers may make aliasing assumptions which are broken by such constructions.

Sadly, alignment requirements can be idiosyncratic. For example on modern arm systems, the regular LDR and STR instructions are unaligned-safe, but there are a number of other memory access instructions that are not. 

I think the reason it fails specifically on the int64_t example is that gcc decides to implement a 64-bit assignment using ldrd/strd, which ,on modern arm, have stricter alignment requirements than regular load and store instructions.

As I understand it arm32 kernels have code to fixup unaligned acesses kernel side, but at least some arm64 kernels do not.

Unfortunately there does not seem to be a good solution that is safe, portable and optimal. memcpy is safe and portable, but apparently compilers sometimes fail to optimize it. I have no idea how performance-critical or not this part of the code is.

https://stackoverflow.com/questions/48312068/fast-memcpy-for-small-unaligned-data#comment106102253_48312068

**Comment by plugwash** [comment]
Note: the offending code I mentioned in my previous post was actually.

    value = *reinterpret_cast<const int64_t*>(uValue);

Github apparently decided to intepret the asterisks as formatting markers.

I posted an untested patch at https://github.com/plugwash/linbox/commit/583d6c88c466f83724114042d9f5eeab12a24acc if people want to try it out.

**Comment by plugwash** [comment]
Sorry just noticed a typo in my patch, new version at https://github.com/plugwash/linbox/commit/c63a0ed3b1eb78a5274d6a9c40ae95a3eaeb6f0d

**Comment by tobihan** [comment]
Thank you, that fixed test-serialization, but not the bus errors in test-regression and test-smith-form-valence. Could the reinterpret_cast's in serialize (in addition to the patched ones in unserialize) also be problematic?

**Comment by plugwash** [comment]
> Thank you, that fixed test-serialization, 

good to hear.

> but not the bus errors in test-regression and test-smith-form-valence. 

i don't have a test setup handy, nor am I familiar with linbox's build system. So it's tricky for me to debug stuff myself.

Can you get backtraces showing where in the code the crashes are happening?

> Could the reinterpret_cast's in serialize (in addition to the patched ones in unserialize) also be problematic?

I think those are OK. uint8_t is an alias for unsigned char. A char can never be unaligned and there are special rules allowing char's to alias anything.

**Comment by tobihan** [comment]
As a test setup I was just using amdahl.debian.org and following https://dsa.debian.org/doc/schroot/

Don't you have access there too? If not I'll try to get the backtraces later.

**Comment by plugwash** [comment]
I do have access there, what I'm lacking is any knowlege of linbox's build/test system, if you can provide advice on how to run an individual test in a debugger I can try to take a look when I have time.

**Comment by tobihan** [comment]
Both of the remaining tests crash at this point:

0x0047c2bc in LinBox::BlasMatrixApplyDomain<Givaro::ZRing<Givaro::Integer>, LinBox::BlasMatrix<Givaro::ZRing<Givaro::Integer>, std::vector<Givaro::Integer, std::allocator<Givaro::Integer> > > >::applyV (
    this=0xfffee6b8, y=..., x=..., b=...) at ../linbox/blackbox/apply.h:623
623								for (size_t j=0; j<_n; j++) {

And indeed, the block starting there (and others in that file) contain reinterpret_cast<long long*>.
Could you prepare a patch for that please?

In case you need to debug, I just ran dpkg-buildpackage and then
cd tests && gdb --args bash test-smith-form-valence

**Comment by plugwash** [comment]
I put together a patch. I'm now testing if it builds in an armhf chroot on amdahl

Some of the code I was patching looked highly dubious to start with though, for example performing an operation on 8 bytes at a time, but moving forward in memory by only 4 bytes at a time.

**Comment by plugwash** [comment]
I have now posted a debdiff at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944055#17 , more details over there.

**Comment by tobihan** [comment]
Thanks a lot. I uploaded the patched package to Debian.
@upstream, are you interested in applying this patch? It can be found at
https://salsa.debian.org/science-team/linbox/blob/master/debian/patches/replace-dangerous-pointer-casts-with-memcpy.patch
