### ISSUE TITLE
Hadamard bound computation

### ISSUE THREAD

**Issue by dsroche** [linbox-team/linbox#70]
We need upper bounds on the absolute value of the determinant (over fields such as integers, rational, or polynomials). We propose to make a new solution for a determinant bound. Specifically, it should return a bound on the bit-length of the determinant. (For finite fields should it just return 1? For polynomial fields it should be instead the degree plus one?)

**Comment by gmh33** [comment]
There's a method for polynomials (not Hadamard, but close) in [poly-smith-form.h](https://github.com/linbox-team/linbox/blob/a49ec2d4e661a44e0b9c4d7f16ea78aff1813e8e/linbox/algorithms/poly-smith-form.h#L195).

It uses min(sum(max degree per row), sum(max degree per col)) + 1.  This could be greater than Hadamard's because of cancelation, but it is efficient.

**Comment by Breush** [comment]
Done in #160
